---
disabled_rules:
- variable_name
- force_try
- type_name
- force_cast
- todo
included:
- init 
excluded:
- Pods
file_length:
- 1300
- 2000
line_length:
- 300
- 400
function_body_length:
- 100
- 150
type_body_length:
- 400
- 1000
cyclomatic_complexity:
- 20
- 25
function_parameter_count:
- 10
- 15
